dbt_bigquery_data_pipeline:
  outputs:
    dev:
      dataset: dev_healthcare_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: airflow-dbt-gcp
      threads: 1
      type: bigquery
  target: dev
healthcare_dbt_gcp:
  outputs:
    dev:
      dataset: dev_healthcare_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp/service_account.json
      location: EU
      method: service-account
      priority: interactive
      project: airflow-dbt-gcp
      threads: 1
      type: bigquery
  target: dev
